### ISSUE TITLE
License for mistune-contrib

### ISSUE THREAD

**Issue by vlopezj** [lepture/mistune-contrib#6]
I could not find a LICENSE file in this repo.
Perhaps it is meant to have the same license as `mistune` proper (?).

**Comment by vc12345679** [comment]
You may find the author's declaration [here](https://lepture.com/about).

> Projects
> All open source can be found on [GitHub](https://github.com/lepture), and they are all under BSD License, except that I have declared it under another License.

**Comment by martin-sucha** [comment]
@takluyver Could you please explicitly state the licence for `passthrough.py`? Ideally as a PR with the legal text of the license at the top of the file, so that the file can be copied standalone. `passthrough.py` looks like exactly the thing I could use in my project, but unfortunately can't as it's not clear which license applies, if any.

@lepture It would also help to have a proper LICENSE file in this repo since the statement on your website is ambiguous (i.e. which version of the BSD license applies? also as I read the statement it only applies to `All open source`, but it's not defined what that means exactly).

**Comment by lepture** [comment]
It is BSD. See setup.py

**Comment by martin-sucha** [comment]
Thank you for quick response. `setup.py` only contains `license='BSD'` and `classifiers=[..., 'License :: OSI Approved :: BSD License',...]`, but this does not say which BSD license applies (4-clause, 3-clause, 2-clause? See https://en.wikipedia.org/wiki/BSD_licenses). Could you please add full copy of the license you mean by `BSD` to the repository to avoid any ambiguity?

**Comment by takluyver** [comment]
For my part, I'm fine with `passthrough.py` being under the 2-clause or 3-clause BSD license.
